bot:
  token: 6690948530:AAGr2EcgCeCkvoCFUhQO0iTjWXCi2MxLGtc
  username: BotKolejnyBot
# 6023868622:AAGz3vsK9Zmk4fWW3-jnU8J981fWBLKcTQ8
#  /*SasLog_bot*/
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://google/DB-Chat?cloudSqlInstance=projectsas-402119:us-central1:db-chat
    url: jdbc:postgresql://34.121.209.217:5432/
    #url: jdbc:postgresql://google/DB-Chat?socketFactory=com.google.cloud.sql.postgres
    #.SocketFactory&cloudSqlInstance=projectsas-402119:us-central1:db-chat
    #url: jdbc:postgresql://127.0.0.1:5432/DB-Chat
    username: postgres
    password: Syncmaster
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect